
import { useState } from "react";
import { CheckCircle2Icon, AlertCircleIcon, PlusIcon, ArrowLeftIcon, ArrowRightIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import FormProgress from "@/components/FormProgress";
import TableOfContents from "@/components/TableOfContents";
import { Medication } from "@/components/MedicationItem";
import ClinicalTabsSection from "@/components/review/ClinicalTabsSection";
import PresentingIssuesSection from "@/components/review/PresentingIssuesSection";
import MedicationSection from "@/components/review/MedicationSection";
import SocialHistorySection from "@/components/review/SocialHistorySection";
import FamilyHistorySection from "@/components/review/FamilyHistorySection";
import SectionHeader from "@/components/SectionHeader";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { CitableText } from "@/components/CitationTooltip";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import StepProgress from "@/components/StepProgress";
import { Link, useNavigate } from "react-router-dom";
